@ECHO OFF

SET MY_PATH=%~dp0
REM ECHO %MY_PATH%

SET INPUT_FILE=%1
REM CHECKING IF A VARIABLE IS SET OR NOT
IF NOT DEFINED INPUT_FILE (SET INPUT_FILE="%MY_PATH%input.txt")
ECHO INPUT=%INPUT_FILE%

SET OUTPUT_FILE=%2
IF NOT DEFINED OUTPUT_FILE (SET OUTPUT_FILE="%MY_PATH%output.txt")
ECHO OUTPUT=%OUTPUT_FILE%

openssl enc -aes-256-cbc -in %INPUT_FILE% -out %OUTPUT_FILE% -pass pass:"secret key 123" -e -base64